### ISSUE TITLE
Implement parallel downloads from S3

### ISSUE THREAD

**Issue by senderista** [uwescience/myria#798]
We should make it possible to download a single S3 object to each worker in parallel, with little or no coordination required, and no appreciable burden on the coordinator.

The main idea is to divide the S3 object into as many equal-sized byte ranges as the number of participating workers, and have each worker issue a [byte-range request](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/GetObjectRequest.html#withRange(long, long)) to S3 for its own range. For schemas containing only fixed-length fields, we can calculate the byte ranges to preserve record boundaries. Otherwise, we have two choices:

1. Glue fragments of records spanning adjacent workers together after all downloads have completed (which requires nontrivial coordination).
2. Overlap the byte ranges assigned to each worker, so that the overlap is at least the maximum record size in bytes. We would have to ignore all records completely contained in the last `MAX_RECORD_SIZE` bytes of each worker's range (except for the last worker), as well as all record fragments.

The main advantage of 2) is that it avoids coordination; the main disadvantage is that it requires us to know the maximum record size. A very large default for `MAX_RECORD_SIZE` on the order of several MB should be acceptable, given that each range is likely to be at least 1GB (otherwise we would just stream through the coordinator). Still, the download could silently omit some records if the default was too small. One mitigation would be to either warn the user or fail the query whenever a record was found to exceed `MAX_RECORD_SIZE`. The user could then explicitly specify `MAX_RECORD_SIZE` (presumably in MyriaL syntax).

This would require us to use the low-level S3 API, since existing tools which use the parallel byte-range download strategy assume that the object will be downloaded to a single file. Concretely, we need a new `FileScan`-like operator, which can be initialized with an S3 URL, byte range, and, if approach 2) is implemented, a flag indicating whether it's the final worker (so it doesn't ignore any records in the last `MAX_RECORD_SIZE` bytes of its range). The coordinator would generate all subqueries with this operator, then simply wait for all subqueries to complete, with no further coordination required.

**Comment by senderista** [comment]
@jingjingwang would appreciate your feedback.

**Comment by jingjingwang** [comment]
I suppose that downloading CSV files (and other text files) from S3 is our main use case. The problem is that these files are not binary files, so even if we have fixed-length schema, the # of bytes of storing one record still varies. So in most cases we will be dealing with variable-length records.

I've been trying to figure out a way to get rid of this `MAX_RECORD_SIZE` since I feel it's a pain to the user, especially when the user is not familiar with the data. Here is what I have so far. First, each worker only needs to download its portion with no overlapping as in the first choice, and second, each worker reports the lengths of the head record fragment it has. Let's say they report to the master (although in theory they can talk to each other directly), and the master tells each worker how many bytes it's missing for completing its tail record, which is the # of bytes of the head fragment reported by the worker following. Then each worker issues another request to complete its tail fragment. 

The overhead of making HTTP requests and communicating should be tiny comparing to the cost of downloading, so I hope it's acceptable. There is some implementation complexity for sure, we may need this special S3 download operator to send out a message to master, and to have a child waiting for the message. (It starts to sound like an `IDBController` to me :))

Another wild(er) idea I have is, instead of coordinating, each worker tries to complete its tail fragment directly with some length first, and if it's not enough, double the length. The most extreme case is what if we have a record larger than the partition of a worker. Well...

There is a nitpicking improvement: we don't need the flag indicating if it's the final worker, if we discard the head fragments -- since byte 0 indicates the first worker. 

I didn't really get the point that parallel byte-range download strategy assume that the object will be downloaded to a single file -- if it's a single file on each worker then it sounds like what we need..? But anyway I think we will be using the Java SDK from Amazon anyway, and we will get an `InputStream` object from some API directly with no real file.

**Comment by senderista** [comment]
@jingjingwang thanks for the great feedback! Excellent point about text formats implying de facto variable-length records; I don't know how I missed that. I really like your idea of eliminating coordination by using exponentially increasing ranges to download incomplete records (this is the ubiquitous "galloping search" trick). Since the position of the end of a range within a fragment is, on average, in the middle of the fragment, we should double the initial length of the fragment on each additional request, right? I think we can clearly abort the retry sequence and fail the ingest query when the record fragment size (or the total partition size) exceeds some threshold (so we'll have a `MAX_RECORD_SIZE` regardless, just much less intrusive than with the overlapping ranges approach).

Re: your confusion about my wording "a single S3 object": I meant a single object on the S3 side, not the Myria side. The nice thing about this approach is that the user doesn't have to manually partition their files on S3.

**Comment by jingjingwang** [comment]
I see. If we go with the exponential approach, maybe we can start with a little overlapping by default, like several KBs? Some reasonable number that is good for both covering a record and networking.

**Comment by senderista** [comment]
Yes, a small default overlap seems like a reasonable approach (although it will add a little complexity WRT ignoring any tuples which start in the overlap region, but maybe that's not a big deal given that we also have to discard all fragments from the beginning of the range).

**Comment by senderista** [comment]
We need to address the edge case where there are fewer workers in the cluster than bytes in the dataset, or where partitions would be ridiculously small if we used all workers. We should configure a minimum partition size, and use only as many workers as we need to maintain that minimum partition size, if possible (otherwise we just store on a single worker). Concretely, `num_workers = min(cluster_size, ceil(data_size_bytes/min_partition_size))`.

**Comment by senderista** [comment]
Fixed in #822.
