### ISSUE TITLE
MyriaL: Reference attributes from previously defined selections

### ISSUE THREAD

**Issue by dhutchis** [uwescience/myria#838]
In the following example, I would like to reference the `a2` attribute from the first select expression in the second select expression.  Right now I cannot do so; I am required to write `a*a + 1 as a2p1` instead.

```
T1 = scan(TwitterK);
Agg = [from T1 emit a*a as a2, a2+1 as a2p1];
store(Agg, Twitter_aggregate, [$1]);
```

For this small example, working around the issue is fine.  But in larger use cases like linear interpolation, repeating the expression is tedious.

**Comment by senderista** [comment]
I don't think you can do this in SQL either. The order of attribute expressions in a projection doesn't correspond to a pseudo-imperative evaluation order that would make previously defined attributes available to subsequent attribute expressions. You might be misled by the pseudo-imperative appearance of sequenced assignment statements in MyriaL, but attribute expressions in projections are not similarly sequenced. Is the following equivalent too tedious to write?

```
T1 = scan(TwitterK);
Agg1 = [from T1 emit a*a as a2];
Agg2 = [from Agg1 emit a2+1 as a2p1];
store(Agg2, Twitter_aggregate, [$0]);
```
The Apply operators should be pipelined so that there's no runtime difference between the operator graph for this and what your ideal pseudo-imperative attribute syntax would compile to.

Also, this issue really belongs in raco since MyriaL doesn't exclusively target the MyriaX backend (ideally it should compile to at least Spark as well).

**Comment by billhowe** [comment]
+1 to Tobin's response: Not possible in SQL, and I think it's fine to do it
in two lines.  Much nicer than a nested query or a WITH clause in SQL,
which are also not that bad.

I'd say close this as won't fix or whatever.

**Comment by dhutchis** [comment]
Thanks @senderista and @billhowe.  Indeed when I was writing the more complex interpolation query, I did it in two lines.
